placarfutmesa/base/urls.py
from django.urls import path

from placarfutmesa.base.views import home


app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

placarfutmesa/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('placarfutmesa.base.urls')),
]
if settings.DEBUG:
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls'))
    )

placarfutmesa/base/models.py
from django.core.validators import RegexValidator
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, cpf, password, **extra_fields):
        """
        Create and save a user with the given CPF and password.
        """
        if not cpf:
            raise ValueError("The given username must be set")
        user = self.model(cpf=cpf, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, cpf=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(cpf, password, **extra_fields)

    def create_superuser(self, cpf=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(cpf, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.

    Cpf and password are required. Other fields are optional.
    """
    cpf_validator = RegexValidator(
        regex=r'^\d{11}$',
        message=_("CPF must be exactly 11 digits without punctuation."),
    )

    cpf = models.CharField(
        _("CPF"),
        max_length=11,
        unique=True,
        validators=[cpf_validator],
        help_text=_("Enter your 11-digit CPF without punctuation."),
    )

    first_name = models.CharField(_("first name"), max_length=150, blank=True)
    last_name = models.CharField(_("last name"), max_length=150, blank=True)
    nickname = models.CharField(_("nickname"), max_length=150, blank=True)
    email = models.EmailField(_("email address"), blank=True, null=True)
    association = models.ForeignKey("Associate", on_delete=models.SET_NULL, null=True, blank=True)
    birth_year = models.PositiveIntegerField(_("year of birth"), null=True, blank=True)
    category = models.CharField(_("category"), max_length=50, blank=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "cpf"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        if self.email:
            self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the nickname or short name for the user."""
        return self.nickname if self.nickname != '' else self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Going to email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    # def save(self, *args, **kwargs):
    #     """Automatically set the category based on birth year."""
    #     if self.birth_year:
    #         current_year = timezone.now().year
    #         age = current_year - self.birth_year
    #         if age < 50:
    #             self.category = "Free"
    #         elif 50 <= age < 60:
    #             self.category = "Senior"
    #         else:
    #             self.category = "Master"
    #     super().save(*args, **kwargs)


class Associate(models.Model):
    """Model for associations."""
    acronym = models.CharField(_("acronym"), max_length=20)
    name = models.CharField(_("name"), max_length=150)
    logo = models.ImageField(_("logo"), upload_to="logos/", blank=True, null=True)

    class Meta:
        verbose_name = "Associação"  # Nome no singular
        verbose_name_plural = "Associações"  # Nome no plural

    def __str__(self):
        return self.name

placarfutmesa/base/views.py
# from django.http import HttpResponse
from django.shortcuts import render


class Competition:
    def __init__(self, comp_id, comp_type, comp_name, comp_stage, comp_modality, comp_status):
        self.slug = "".join(comp_name.split())
        self.comp_id = comp_id
        self.comp_type = comp_type
        self.comp_name = comp_name
        self.comp_stage = comp_stage
        self.comp_modality = comp_modality
        self.comp_status = comp_status


competitions = [
        Competition(
            20250319,
            'Campeonato',
            'Campeonato interno',
            'Etapa 2',
            'Cavado',
            'Progress'
        ),
        Competition(
            20250410,
            'Copa',
            'Copa COP',
            '',
            'Cavado',
            'Progress'
        ),
        Competition(
            20250205,
            'Copa',
            'Circulão',
            '',
            'Cavado',
            'Closed'
        ),
]


# Create your views here.
def home(request):
    # return HttpResponse('<html><body>PLACAR - FUTEBOL DE MESA</html></body>', content_type='text/html')
    return render(request, 'base/home.html', context={'competitions': competitions})

placarfutmesa/base/templates/base/home.html
<!doctype html>
{% load static %}
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Página de registro de competições do Círculo Operário Pelotense - COP">
        <meta name="author" content="Michel Alves - Hippo">
        <title>PLACAR - Futebol de Mese</title>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link
                rel="stylesheet"
                href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
                integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
                crossorigin="anonymous"
                referrerpolicy="no-referrer"
        />
        <link rel="icon" type="image/png" href="{% static 'img/decop-icon.png' %}">
    </head>
    <body>
        <div class="container">

            <header>
                <nav id="nav">
                    <a href="{% url 'base:home' %}" class="logo">
                        <img src="{% static 'img/logo_decop.webp' %}" alt="decop-logo">
                    </a>
                    <ul class="menu-list" id="menuList">
                        <li><a href="{% url 'base:home' %}" class="active">Competições</a></li>
                        <li><a href="#">Associações</a></li>
                        <li><a href="#">Jogadores</a></li>
                        <li><a href="#" id="department">Departamento</a></li>
                        <div class="menu-dropdown">
                            <ul class="list-dropdown" id="listDropdown">
                                <li><a href="#">Nova Competição</a></li>
                                <li><a href="#">Registrar Associação</a></li>
                                <li><a href="#">Registrar Jogador</a></li>
                            </ul>
                        </div>
                    </ul>
                    <button class="menu-toggle" id="menuToggle"><i class="fa fa-bars" aria-hidden="true"></i></button>
                </nav>
            </header>

            <div class="carousel-container">
                <div class="carousel-track">
                    <div class="carousel-item">
                        <p>Data: 25/12/2024</p>
                        <h3>Time A 2 x 1 Time B</h3>
                        <p>Campeonato Interno Etapa 2 Cavado</p>
                    </div>
                    <div class="carousel-item">
                        <p>Data: 24/12/2024</p>
                        <h3>Time C 0 x 3 Time D</h3>
                        <p>Campeonato Interno Etapa 2 Cavado</p>
                    </div>
                    <div class="carousel-item">
                        <p>Data: 23/12/2024</p>
                        <h3>Time E 1 x 1 Time F</h3>
                        <p>Campeonato Interno Etapa 2 Cavado</p>
                    </div>
                </div>
            </div>

            <main>
                <div class="card-bx">
                    <div class="in-progress">
                        <h3 class="bx-title">Em andamento:</h3>
                        <div class="in-progress-bx">
                            {% for competition in competitions %}
                                {% if competition.comp_status == 'Progress' %}
                                    <div class="competition-card">
                                        <div class="field-1">
                                            {% if competition.comp_type == 'Campeonato' %}
                                                <i class="fas fa-medal"></i>
                                            {% elif competition.comp_type == 'Copa' %}
                                                <i class="fas fa-trophy"></i>
                                            {% endif %}
                                            <h3 class="comp-title">{{ competition.comp_name | default:'Faltando Nome' }}</h3>
                                            <h4 class="stage">{{ competition.comp_stage | default:'' }}</h4>
                                        </div>
                                        <div class="field-2">
                                            <h4 class="modality">{{ competition.comp_modality | default:'Faltando Modalidade' }}</h4>
                                        </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="closed">
                        <h3 class="bx-title">Encerrados:</h3>
                        <div class="closed-bx">
                            {% for competition in competitions %}
                                {% if competition.comp_status == 'Closed' %}
                                    <div class="competition-card">
                                        <div class="field-1">
                                            {% if competition.comp_type == 'Campeonato' %}
                                                <i class="fas fa-medal"></i>
                                            {% elif competition.comp_type == 'Copa' %}
                                                <i class="fas fa-trophy"></i>
                                            {% endif %}
                                            <h3 class="comp-title">{{ competition.comp_name | default:'Faltando Nome' }}</h3>
                                            <h4 class="stage">{{ competition.comp_stage | default:'' }}</h4>
                                        </div>
                                        <div class="field-2">
                                            <h4 class="modality">{{ competition.comp_modality | default:'Faltando Modalidade' }}</h4>
                                        </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </main>


            <footer>
                <div class="footer">
                    <p>Desenvolvido por: </p>
                    <img src="{% static 'img/hippo_logo.png' %}" alt="">
                </div>
            </footer>






        </div>

        <script src="{% static 'js/scripts.js' %}"></script>

    </body>
</html>